[package]
name = "jalava"
version = "0.1.0"
edition = "2018"

[dependencies]
jalava-derive = { path = "../jalava-derive" }
chrono = { version = "0.4", optional = true }
rocket = { version = "0.5.0-rc.1", optional = true }
uuid = { version = "0.8", optional = true }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
