[package]
name = "jalava-derive"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
heck = "0.3"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
